---
# DESCRIPTION: codecov.io config
#
# Copyright 2020-2025 by Wilson Snyder. This program is free software; you
# can redistribute it and/or modify it under the terms of either the GNU
# Lesser General Public License Version 3 or the Perl Artistic License
# Version 2.0.
# SPDX-License-Identifier: LGPL-3.0-only OR Artistic-2.0
####################
# Validate:
#  curl --data-binary @.codecov.yml https://codecov.io/validate
#
codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false
coverage:
  precision: 2
  range: 70...100
  round: down
comment:
  layout: "condensed_header,condensed_files"
  behavior: new
  hide_project_coverage: true # PR patch coverage only
  require_base: false
