---
# DESCRIPTION: codecov.io config
#
# Copyright 2020-2026 by Wilson Snyder. This program is free software; you
# can redistribute it and/or modify it under the terms of either the GNU
# Lesser General Public License Version 3 or the Perl Artistic License
# Version 2.0.
# SPDX-License-Identifier: LGPL-3.0-only OR Artistic-2.0
####################
# Validate:
#  curl --data-binary @.codecov.yml https://codecov.io/validate
#
coverage:
  precision: 2
  range: 75...100
  round: down
  status:
    project: false
    patch: false
comment: false
