// DESCRIPTION: Verilator: Verilog Test module
//
// This file ONLY is placed under the Creative Commons Public Domain.
// SPDX-FileCopyrightText: 2026 Wilson Snyder
// SPDX-License-Identifier: CC0-1.0

// verilog_format: off
`define input_signal(name, width) input logic [width-1:0] name
`define output_signal(name, width) output logic [width-1:0] name
`define public_array(name, width, lhs, rhs) logic [width-1:0] name[lhs:rhs] /*verilator public_flat_rw*/
`define public_signal(name, width) logic [width-1:0] name /*verilator public_flat_rw*/
// verilog_format: on

module t (
    `include "portlist.vh"  // Boilerplate generated by the Python driver
);
  `input_signal(x, 1);
  `input_signal(z, 1);
  `input_signal(data, 7);
  `output_signal(constant_out, 1);
  `output_signal(feedback_out, 1);
  `output_signal(packed_out, 7);
  `output_signal(array_out, 7);

  `public_signal(constant_value, 1);
  always_comb begin
    constant_value = x;
    constant_out = constant_value && z;
    constant_value = 1'b0;
  end

  `public_signal(feedback_value, 1);
  logic feedback;
  assign feedback = z && feedback_value;
  always_comb begin
    feedback_value = x;
    feedback_out = feedback_value && feedback;
  end

  `public_signal(packed_value, 7);
  always_comb begin
    packed_value[0] = data[0];
    packed_out = packed_value;
    packed_value[0] = ~data[0];
  end

  `public_array(array_value, 7, 2, 3);
  always_comb begin
    array_value[2] = data;
    array_out = array_value[3];
    array_value[2] = ~data;
  end
endmodule
