#!/usr/bin/env python3
# DESCRIPTION: Verilator: Verilog Test driver/expect definition
#
# Stress test for interface typedef scaling.  Generates an interface with
# many typedefs and two parameterised instances to exercise the
# findTypedefInModule / findDTypeInModule caching path.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of either the GNU Lesser General Public License Version 3
# or the Perl Artistic License Version 2.0.
# SPDX-FileCopyrightText: 2026 Wilson Snyder
# SPDX-License-Identifier: LGPL-3.0-only OR Artistic-2.0

import time

import vltest_bootstrap

test.scenarios('vlt')
test.top_filename = test.obj_dir + "/t_iface_typedef_scale.sv"

N_TYPEDEFS = 5000
MAX_COMPILE_SECS = 10  # Generous budget; catches O(N^2) explosion where 5k typedefs would take minutes without the cache


def gen(filename, n):
    with open(filename, 'w', encoding="utf8") as fh:
        fh.write("// Generated by t_iface_typedef_scale.py\n")
        fh.write("// Stress test: interface with {} typedefs, two instances\n".format(n))
        fh.write("\n")
        # Interface with N typedefs
        fh.write("interface iface_many_types #(parameter int CFG = 8);\n")
        for i in range(n):
            fh.write("  typedef logic [CFG-1:0] td_{};\n".format(i))
        fh.write("endinterface\n\n")
        # Module that uses the interface and references typedefs via the port
        fh.write("module sub (\n")
        fh.write("  iface_many_types ifc,\n")
        fh.write("  input logic clk\n")
        fh.write(");\n")
        fh.write("  typedef ifc.td_0 local_td_0;\n")
        fh.write("  typedef ifc.td_{} local_td_n;\n".format(n - 1))
        fh.write("  local_td_0 r0;\n")
        fh.write("  local_td_n rn;\n")
        fh.write("  always @(posedge clk) begin\n")
        fh.write("    r0 <= '0;\n")
        fh.write("    rn <= '0;\n")
        fh.write("  end\n")
        fh.write("endmodule\n\n")
        # Top module with two instances using different parameters
        fh.write("module t (input logic clk);\n")
        fh.write("  iface_many_types #(.CFG(16)) ifc_a();\n")
        fh.write("  iface_many_types #(.CFG(32)) ifc_b();\n")
        fh.write("  sub sub_a (.ifc(ifc_a), .clk(clk));\n")
        fh.write("  sub sub_b (.ifc(ifc_b), .clk(clk));\n")
        fh.write("  initial begin\n")
        fh.write('    $write("*-* All Finished *-*\\n");\n')
        fh.write("    $finish;\n")
        fh.write("  end\n")
        fh.write("endmodule\n")


gen(test.top_filename, N_TYPEDEFS)

t0 = time.time()
test.compile(verilator_flags2=["-x-assign fast --x-initial fast"])
elapsed = time.time() - t0

print("t_iface_typedef_scale: {} typedefs compiled in {:.3f}s (limit {:.1f}s)".format(
    N_TYPEDEFS, elapsed, MAX_COMPILE_SECS))
if elapsed > MAX_COMPILE_SECS:
    test.error("Compile took {:.3f}s, exceeds {:.1f}s budget for {} typedefs".format(
        elapsed, MAX_COMPILE_SECS, N_TYPEDEFS))

test.execute()

test.passes()
