// DESCRIPTION: Verilator: External clock aliases are not generated by a subgraph
//
// This file ONLY is placed under the Creative Commons Public Domain.
// SPDX-FileCopyrightText: 2026 Wilson Snyder
// SPDX-License-Identifier: CC0-1.0

// verilog_format: off
`define stop $stop
`define checkh(gotv,expv) do if ((gotv) !== (expv)) begin $write("%%Error: %s:%0d: got=%0x exp=%0x (%s !== %s)\n", `__FILE__,`__LINE__, (gotv), (expv), `"gotv`", `"expv`"); `stop; end while (0)
// verilog_format: on

module t (
  input logic clk
);
  logic clk2 /*verilator public_flat*/;
  int unsigned cycles = 0;
  wire [6:0] q0;
  wire [6:0] q1;
  logic [6:0] observed /*verilator public_flat*/;
  function automatic logic [6:0] observe(input logic [6:0] a, input logic [6:0] b);
    // verilator no_inline_task
    return a ^ b;
  endfunction
  always_comb begin
    clk2 = clk;
    observed = observe(q0, q1);
  end
  sg_clock_alias i0 (.clk(clk2), .q(q0));
  sg_clock_alias i1 (.clk(clk2), .q(q1));
  always_ff @(posedge clk2) begin
    `checkh(q0, 7'(cycles + 1));
    `checkh(q1, 7'(cycles + 1));
    `checkh(observed, q0 ^ q1);
    if (cycles == 20) begin
      $write("*-* All Finished *-*\n");
      $finish;
    end
    cycles <= cycles + 1;
  end
endmodule

module sg_clock_alias (input logic clk, output logic [6:0] q = 1);
  /*verilator subgraph_boundary*/
  wire clk2;
  assign clk2 = clk;
  logic [6:0] next_q;
  always_comb next_q = q + 7'(clk2);
  always_ff @(posedge clk) q <= next_q;
endmodule
