#!/usr/bin/env python3
# DESCRIPTION: Verilator: Verilog Test driver/expect definition
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of either the GNU Lesser General Public License Version 3
# or the Perl Artistic License Version 2.0.
# SPDX-FileCopyrightText: 2026 Wilson Snyder
# SPDX-License-Identifier: LGPL-3.0-only OR Artistic-2.0

import vltest_bootstrap

test.scenarios('vlt_all')
test.top_filename = test.obj_dir + '/t_variable_order_single_worker.v'

# This fixture retains two shared banks with different writers on one worker,
# plus private banks and the output accessed only by the other worker.
with open(test.top_filename, 'w', encoding='utf8') as fh:
    fh.write('// Generated by t_variable_order_single_worker.py\n')
    fh.write('module t(input logic clk, input logic [7:0] i, output logic [31:0] o);\n')
    for index in range(32):
        fh.write(f'  logic [31:0] r{index};\n')
    for index in range(32):
        fh.write(f'  always_ff @(posedge clk) r{index} <= '
                 f"(r{index} + {{24'd0, i}}) ^ 32'h{index + 1:08x};\n")
    fh.write("  always_comb o = 32'h0" + ''.join(f' ^ r{i}' for i in range(32)) + ';\n')
    fh.write('endmodule\n')

flags = [
    '--cc', '--stats', '--dumpi-V3VariableOrder 1', '-Wno-UNOPTTHREADS', '--threads-max-mtasks',
    '8'
]
test.compile(verilator_flags2=flags,
             threads=(2 if test.vltmt else 1),
             make_main=False,
             make_top_shell=False,
             verilator_make_gmake=False)
if test.vltmt:
    # Review intentional scheduling changes before updating counts or goldens.
    test.oprint('Layout expectation changes: see docs/internals.rst, Variable Layout.')
    dump = test.glob_one(test.obj_dir + '/*_variableorder.txt')
    test.files_identical(dump, 't/t_variable_order_single_worker.out')
    # Clearing all writer identities would also merge the two shared banks.
    test.file_grep(test.stats, r'VariableOrder, MTask affinity groups\s+(\d+)', 4)
    test.file_grep(test.stats, r'VariableOrder, MTask aligned group starts\s+(\d+)', 4)
    test.file_grep(test.stats, r'VariableOrder, no-affinity variables\s+(\d+)', 10)
    test.file_grep(test.stats, r'VariableOrder, single-worker variables\s+(\d+)', 17)
    test.file_grep(test.stats, r'VariableOrder, shared read-only variables\s+(\d+)', 2)
    test.file_grep(test.stats, r'VariableOrder, shared written variables\s+(\d+)', 16)
    test.file_grep(test.stats, r'VariableOrder, groups eliminated by worker affinity\s+(\d+)', 1)
    test.file_grep(test.stats,
                   r'VariableOrder, groups eliminated for single-worker variables\s+(\d+)', 2)
    test.file_grep(test.stats, r'VariableOrder, additional groups for shared writers\s+(\d+)', 2)

    # Dumping without --stats must still gather affinities and produce the same layout.
    dump_dir = test.obj_dir + '/dump_only'
    dump_flags = flags + ['--no-stats', '--no-skip-identical', '--Mdir', dump_dir]
    test.compile(verilator_flags2=dump_flags,
                 threads=2,
                 make_main=False,
                 make_top_shell=False,
                 verilator_make_gmake=False)
    dump = test.glob_one(dump_dir + '/*_variableorder.txt')
    test.files_identical(dump, 't/t_variable_order_single_worker.out')
    if os.path.exists(dump_dir + '/' + test.vm_prefix + '__stats.txt'):
        test.error('Dump-only compilation unexpectedly produced statistics')

    # A directory at the discovered dump path makes opening it fail, even as root.
    # Discover the filename instead of relying on its internal stage number.
    test.unlink_ok(dump)
    test.mkdir_ok(dump)
    try:
        test.compile(verilator_flags2=dump_flags,
                     threads=2,
                     make_main=False,
                     make_top_shell=False,
                     verilator_make_gmake=False,
                     fails=True)
        test.file_sed(test.obj_dir + '/vlt_compile.log', test.obj_dir + '/dump_bad.log',
                      lambda text: text.replace(dump, '<layout dump>'))
        test.files_identical(test.obj_dir + '/dump_bad.log',
                             't/t_variable_order_single_worker__dump_bad.out',
                             is_logfile=True)
    finally:
        os.rmdir(dump)
else:
    test.file_grep_not(test.stats, r'VariableOrder, MTask affinity groups')
    test.file_grep_not(test.stats, r'VariableOrder, MTask aligned group starts')

test.passes()
