#!/usr/bin/env python3
# DESCRIPTION: Verilator: Verilog Test driver/expect definition
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of either the GNU Lesser General Public License Version 3
# or the Perl Artistic License Version 2.0.
# SPDX-FileCopyrightText: 2026 Wilson Snyder
# SPDX-License-Identifier: LGPL-3.0-only OR Artistic-2.0

import vltest_bootstrap

test.scenarios('vlt_all')
test.top_filename = test.obj_dir + "/t_variable_order_mtask.v"


def gen(filename, nregs):
    with open(filename, 'w', encoding="utf8") as fh:
        fh.write("// Generated by t_variable_order_mtask.py\n")
        fh.write("module t(input logic clk, input logic [7:0] i, output logic [31:0] o[8]);\n")
        for i in range(nregs):
            fh.write(f"  logic [31:0] r{i};\n")
        for i in range(nregs):
            fh.write("  always_ff @(posedge clk) begin\n")
            fh.write(f"    r{i} <= (r{i} + {{24'd0, i}}) ^ 32'h{i + 1:08x};\n")
            fh.write("  end\n")
        for k in range(8):
            # r0 has an extra reader, on the same worker as r8's reader.
            regs = list(range(k, nregs, 8)) + ([0] if k == 7 else [])
            fh.write(f"  assign o[{k}] = " + " ^ ".join(f"r{i}" for i in regs) + ";\n")
        fh.write("endmodule\n")


gen(test.top_filename, 24)

flags = ["--cc", "--stats", "--dumpi-V3VariableOrder 1", "-Wno-UNOPTTHREADS"]
if test.vltmt:
    flags += ["--threads-max-mtasks 16"]

test.compile(verilator_flags2=flags, threads=(2 if test.vltmt else 1))

headers = test.glob_some(test.obj_dir + "/" + test.vm_prefix + "_*.h")
aligned_var_re = r'alignas\(VL_CACHE_LINE_BYTES\) (?:CData|SData|IData|QData|VlWide|VL_)'

if test.vltmt:
    test.file_grep_any(headers, aligned_var_re)
    # The dump records different accessing tasks but the same workers/writer
    # for r0 and r8, and their placement in the same final group.
    dump = test.glob_one(test.obj_dir + '/*_variableorder.txt')
    test.files_identical(dump, 't/t_variable_order_mtask.out')
    # Merge private banks while retaining exact writer distinctions for shared banks.
    test.file_grep(test.stats, r'VariableOrder, MTask affinity groups\s+(\d+)', 8)
    test.file_grep(test.stats, r'VariableOrder, MTask aligned group starts\s+(\d+)', 8)
    test.file_grep(test.stats, r'VariableOrder, no-affinity variables\s+(\d+)', 11)
    test.file_grep(test.stats, r'VariableOrder, single-worker variables\s+(\d+)', 11)
    test.file_grep(test.stats, r'VariableOrder, shared read-only variables\s+(\d+)', 2)
    test.file_grep(test.stats, r'VariableOrder, shared written variables\s+(\d+)', 14)
    test.file_grep(test.stats, r'VariableOrder, groups eliminated by worker affinity\s+(\d+)', 2)
    test.file_grep(test.stats,
                   r'VariableOrder, groups eliminated for single-worker variables\s+(\d+)', 5)
    test.file_grep(test.stats, r'VariableOrder, additional groups for shared writers\s+(\d+)', 6)
else:
    for header in headers:
        test.file_grep_not(header, aligned_var_re)
    test.file_grep_not(test.stats, r'VariableOrder, MTask affinity groups')
    test.file_grep_not(test.stats, r'VariableOrder, MTask aligned group starts')

test.passes()
