#!/usr/bin/env python3
# DESCRIPTION: Verilator: Verilog Test driver/expect definition
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of either the GNU Lesser General Public License Version 3
# or the Perl Artistic License Version 2.0.
# SPDX-FileCopyrightText: 2026 Wilson Snyder
# SPDX-License-Identifier: LGPL-3.0-only OR Artistic-2.0

import vltest_bootstrap

import re

test.scenarios('vlt_all')
test.top_filename = test.obj_dir + "/t_variable_order_mtask.v"


def gen(filename, nregs):
    with open(filename, 'w', encoding="utf8") as fh:
        fh.write("// Generated by t_variable_order_mtask.py\n")
        fh.write("module t(input logic clk, input logic [7:0] i, output logic [31:0] o[8]);\n")
        for i in range(nregs):
            fh.write(f"  logic [31:0] r{i};\n")
        for i in range(nregs):
            fh.write("  always_ff @(posedge clk) begin\n")
            fh.write(f"    r{i} <= (r{i} + {{24'd0, i}}) ^ 32'h{i + 1:08x};\n")
            fh.write("  end\n")
        for k in range(8):
            # r0 has an extra reader, on the same worker as r8's reader.
            regs = list(range(k, nregs, 8)) + ([0] if k == 7 else [])
            fh.write(f"  assign o[{k}] = " + " ^ ".join(f"r{i}" for i in regs) + ";\n")
        fh.write("endmodule\n")


gen(test.top_filename, 24)

flags = ["--cc", "--stats", "-Wno-UNOPTTHREADS"]
if test.vltmt:
    flags += ["--threads-max-mtasks 16"]

test.compile(verilator_flags2=flags, threads=(2 if test.vltmt else 1))

root_h = test.obj_dir + "/" + test.vm_prefix + "___024root.h"
aligned_var_re = r'alignas\(VL_CACHE_LINE_BYTES\) (?:CData|SData|IData|QData|VlWide|VL_)'

if test.vltmt:
    test.file_grep(root_h, aligned_var_re)
    # Verify the fixture still exercises different reader tasks on one worker,
    # with the same writing task. Do not depend on specific task or worker IDs.
    functions = {}
    for filename in test.glob_some(test.obj_dir + '/' + test.vm_prefix + '___024root*.cpp'):
        with open(filename, encoding='utf8') as fh:
            functions.update(
                re.findall(r'^void (\w+)\([^;{]*\) \{\n(.*?)^\}', fh.read(), re.S | re.M))
    tasks = {name: body for name, body in functions.items() if re.search(r'__nba_mtask\d+$', name)}
    workers = {
        task: name
        for name, body in functions.items() if '____Vthread' in name for task in tasks
        if task + '(' in body
    }
    accesses = [{
        task
        for task, body in tasks.items() if re.search(r'\bt__DOT__r' + str(reg) + r'\b', body)
    } for reg in (0, 8)]
    writers = [{
        task
        for task, body in tasks.items() if re.search(r'\bt__DOT__r' + str(reg) + r'\s*=', body)
    } for reg in (0, 8)]
    if len(writers[0]) != 1 or writers[0] != writers[1] or accesses[0] == accesses[1]:
        test.error('Fixture needs one shared writer and different reader tasks for r0 and r8')
    if any(task not in workers for access in accesses for task in access):
        test.error('Fixture task has no scheduled worker')
    elif {workers[task] for task in accesses[0]} != {workers[task] for task in accesses[1]}:
        test.error('Fixture needs identical accessing workers for r0 and r8')

    # r0 and r8 must share a group despite their different reader-task sets.
    groups = [
        set(re.findall(r'\bt__DOT__r(\d+);', group))
        for group in test.file_contents(root_h).split('alignas(VL_CACHE_LINE_BYTES)')
    ]
    if not any({'0', '8'} <= group for group in groups):
        test.error('Different reader tasks split written fields r0 and r8 into separate groups')
    # Merge private banks while retaining exact writer distinctions for shared banks.
    test.file_grep(test.stats, r'VariableOrder, MTask affinity groups\s+(\d+)', 8)
    test.file_grep(test.stats, r'VariableOrder, MTask aligned group starts\s+(\d+)', 8)
else:
    test.file_grep_not(root_h, aligned_var_re)
    test.file_grep_not(test.stats, r'VariableOrder, MTask affinity groups')
    test.file_grep_not(test.stats, r'VariableOrder, MTask aligned group starts')

test.passes()
