#!/usr/bin/env python3
# DESCRIPTION: Verilator: Verilog Test driver/expect definition
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of either the GNU Lesser General Public License Version 3
# or the Perl Artistic License Version 2.0.
# SPDX-FileCopyrightText: 2026 Wilson Snyder
# SPDX-License-Identifier: LGPL-3.0-only OR Artistic-2.0

import vltest_bootstrap

test.scenarios('vlt')

test.top_filename = test.obj_dir + "/t_vpi_struct_members_many.v"


def gen(filename, n):
    with open(filename, 'w', encoding="utf8") as fh:
        fh.write("// Generated by t_vpi_struct_members_many.py\n")
        fh.write("module t;\n")
        fh.write("`ifdef VERILATOR\n")
        fh.write("`systemc_header\n")
        fh.write("  extern \"C\" int mon_check(int nmembers);\n")
        fh.write("`verilog\n")
        fh.write("`endif\n")
        # Packed, so the members are only VPI table entries, without C++ struct fields
        fh.write("  typedef struct packed {\n")
        fh.write("    logic a;\n")
        fh.write("    logic b;\n")
        fh.write("  } leaf_t;\n")
        fh.write("  typedef struct packed {\n")
        for i in range(n):
            fh.write("    leaf_t m" + str(i) + ";\n")
        fh.write("  } big_t;\n")
        fh.write("  big_t big  /*verilator public_flat_rw*/;\n")
        fh.write("  int status;\n")
        fh.write("  initial begin\n")
        fh.write("    status = $c32(\"mon_check(" + str(n) + ")\");\n")
        fh.write("    if (status != 0) begin\n")
        fh.write(
            "      $write(\"%%Error: t_vpi_struct_members_many.cpp: mon_check failed\\n\");\n")
        fh.write("      $stop;\n")
        fh.write("    end\n")
        fh.write("    $write(\"*-* All Finished *-*\\n\");\n")
        fh.write("    $finish;\n")
        fh.write("  end\n")
        fh.write("endmodule\n")


gen(test.top_filename, 10000)

# Iterating every member's members must not scan the whole scope each time
test.timeout(120)

test.compile(make_top_shell=False,
             make_main=False,
             make_pli=True,
             verilator_flags2=["--binary --vpi", test.pli_filename])

test.execute(use_libvpi=True, check_finished=True)

test.passes()
