#!/bin/sh
# $Id:$
# DESCRIPTION: Verilator: Invoke linting
#
# Copyright 2003 by Wilson Snyder. This program is free software; you can
# redistribute it and/or modify it under the terms of either the GNU
# General Public License or the Perl Artistic License.

$DIRPROJECT_PREFIX/bin/vlint --brief \
    +librescan +libext+.v -y . +incdir+../include \
    --filt=STMINI,_NETNM,CWCCXX,CSYBEQ,CSEBEQ,NBAJAM,ITENST,STMFOR \
    $*
