#!/bin/bash
######################################################################
# DESCRIPTION: Fuzzer one-line setup & run
#
# Copyright 2019-2019 by Eric Rippey. This program is free software; you
# can redistribute it and/or modify it under the terms of either the GNU
# Lesser General Public License Version 3 or the Perl Artistic License
# Version 2.0.
# SPDX-License-Identifier: LGPL-3.0-only OR Artistic-2.0
######################################################################

# Run all steps needed to configure and start fuzzer
# Note that this assumes the system is a Debian-like Linux distrubution

set -e

sudo ./setup_root
./setup_user
./run
