#!/bin/bash
######################################################################
# DESCRIPTION: Fuzzer run script
#
# SPDX-FileCopyrightText: 2019 Eric Rippey
# SPDX-License-Identifier: LGPL-3.0-only OR Artistic-2.0
######################################################################

# Actually do the fuzzing.  Note that this will not terminate in any reasonable
# amount of time.  However, it will give updates on its progress.
afl-fuzz -i in1 -o out1 -x dictionary ./wrapper --cc @@
