#include<unistd.h>
#include<cstdlib>
#include<cassert>

/*
The purpose of this script is to make sure that the results folder that is 
generated by running verilator does not change the results of subsequent
runs.  

This does slow down the execution do some degree but makes the results more
reliable.  
*/

int main(int argc,char **argv,char **envp){
	auto r=system("rm -rf obj_dir");
	assert(r==0);
	return execve("../../bin/verilator_bin",argv,envp);
}
