#!/usr/bin/perl -w
#$Id$
######################################################################
#
# Copyright 2008-2008 by Wilson Snyder.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of either the GNU General Public License or the
# Perl Artistic License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the Perl Artistic License
# along with this module; see the file COPYING.  If not, see
# www.cpan.org
#                                                                           
######################################################################

# DESCRIPTION: Edits bison output to get around various issues.

foreach my $line (<STDIN>) {
    # Fix bison 2.3 and GCC 4.2.1
    $line =~ s!\(YY_\("!(YY_((char*)"!g;
    print "$line";
}
