#!/usr/bin/env python3
# mypy: disallow-untyped-defs
# pylint: disable=C0114,C0301
######################################################################
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of either the GNU Lesser General Public License Version 3
# or the Perl Artistic License Version 2.0.
# SPDX-FileCopyrightText: 2002-2026 Wilson Snyder
# SPDX-License-Identifier: LGPL-3.0-only OR Artistic-2.0
#
######################################################################
# DESCRIPTION: Edits flex output to get around various broken flex issues.

import os
import re
import subprocess
import sys
import platform


def _flexlexer_uses_size_t() -> bool:
    """Return True if the FlexLexer.h that will be used declares LexerInput with size_t."""
    candidates = []
    env_paths = os.environ.get("CPATH", "") + os.pathsep + os.environ.get("CPLUS_INCLUDE_PATH", "")
    for d in env_paths.split(os.pathsep):
        if d:
            candidates.append(os.path.join(d, "FlexLexer.h"))
    if platform.system() == "Darwin":
        try:
            sdk = subprocess.check_output(["xcrun", "--show-sdk-path"],
                                          stderr=subprocess.DEVNULL).decode().strip()
            if sdk:
                candidates.append(os.path.join(sdk, "usr", "include", "FlexLexer.h"))
        except (OSError, subprocess.CalledProcessError):
            pass
        candidates.extend([
            "/opt/homebrew/include/FlexLexer.h",
            "/usr/local/include/FlexLexer.h",
        ])
    candidates.extend(["/usr/include/FlexLexer.h"])
    for path in candidates:
        try:
            with open(path, "r", encoding="utf-8", errors="ignore") as fh:
                text = fh.read()
        except OSError:
            continue
        if re.search(r"\bLexerInput\s*\(\s*char\s*\*\s*\w*\s*,\s*size_t\b", text):
            return True
        if re.search(r"\bLexerInput\s*\(\s*char\s*\*\s*\w*\s*,\s*int\b", text):
            return False
    return False


_LEXER_USES_SIZE_T = _flexlexer_uses_size_t()

for line in sys.stdin:
    # Fix flex 2.6.1 warning
    line = re.sub(r'for \( i = 0; i < _yybytes_len; \+\+i \)',
                  r'for ( i = 0; (yy_size_t)(i) < (yy_size_t)(_yybytes_len); ++i )', line)
    # Fix flex 2.6.0+ sign comparison warnings
    line = re.sub(
        r'\(\(int\) \(\(yy_n_chars\) \+ number_to_move\) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size\)',
        r'((int) ((yy_n_chars) + number_to_move) > (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size)',
        line)
    line = re.sub(r' number_to_move == YY_MORE_ADJ ', r' (int)number_to_move == (int)YY_MORE_ADJ ',
                  line)
    line = re.sub(
        r'\(\(\(yy_n_chars\) \+ number_to_move\) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size\)',
        r'(((int)(yy_n_chars) + (int)number_to_move) > (int)YY_CURRENT_BUFFER_LVALUE->yy_buf_size)',
        line)
    # Fix flex 2.5.4 namespace omission
    line = re.sub(r'^class istream;', '#include <iostream>\nusing namespace std;\n', line)
    # Fix flex 2.5.31 redefinition
    line = re.sub(r'(\#define\s+yyFlexLexer\s+yyFlexLexer)', r'//flexfix: \1', line)
    # Fix flex 2.5.1 yytext_ptr undef
    line = re.sub(r'(\#undef\s+yytext_ptr)', r'//flexfix: \1', line)
    # Fix flex 2.5.4 and GCC 4.1.0 warn_unused_result
    line = re.sub(r'\(void\) *fwrite\((.*)\)', r'if (fwrite(\1)) {}', line)
    # Fix flex 2.5.33 and GCC 4.1.2 "warning: comparison between signed and unsigned integer expressions" in YY_INPUT
    line = re.sub(r'for \( n = 0; n < max_size && ',
                  r'for ( n = 0; ((size_t)n < (size_t)max_size) && ', line)
    # Fix flex 2.5.4 and GCC 4.0.2 under FLEX_DEBUG
    line = re.sub(r'--accepting rule at line %d ', r'--accepting rule at line %ld ', line)
    # Fix compiler warning filenames
    line = re.sub(r'(#line \d+ ".*)_pretmp', r'\1', line)
    # Fix 'register' storage class specifier is deprecated and incompatible with C++17
    line = re.sub(r'register ', '', line)
    # Change int to size_t on LexerInput/LexerOutput when the FlexLexer.h in use
    # declares them with size_t (e.g. macOS Tahoe's system flex). Skip when the
    # actual FlexLexer.h still uses int (e.g. Homebrew flex 2.6.4) to avoid an
    # out-of-line-definition mismatch.
    if _LEXER_USES_SIZE_T:
        if "::LexerInput(" in line or "::LexerOutput(" in line:
            line = re.sub(r'int ', r'size_t ', line)

    print(line, end='')
