#!/usr/bin/env perl
# See copyright, etc in below POD section.
######################################################################

use warnings;
use strict;

#======================================================================
# main

eval `modulecmd perl add cds-ius`;
exec('iccr',@ARGV);

#######################################################################
__END__

=pod

=head1 NAME

invoke_iccr - Invoke tool under "modules" command

=head1 SYNOPSIS

  invoke_iccr  {ncv arguments}

=head1 DESCRIPTION

=head1 DISTRIBUTION

Copyright 2007-2020 by Wilson Snyder. This program is free software; you
can redistribute it and/or modify it under the terms of either the GNU
Lesser General Public License Version 3 or the Perl Artistic License
Version 2.0.

SPDX-License-Identifier: LGPL-3.0-only OR Artistic-2.0

=head1 AUTHORS

Wilson Snyder <wsnyder@wsnyder.org>

=head1 SEE ALSO

=cut

######################################################################
### Local Variables:
### compile-command: "./invoke_iccr -help"
### End:
