#!/usr/bin/perl -w
# See copyright, etc in below POD section.
######################################################################

require 5.006_001;
use strict;

#======================================================================
# main

eval `modulecmd perl add cds-ius`;
exec('iccr',@ARGV);

#######################################################################
__END__

=pod

=head1 NAME

invoke_iccr - Invoke tool under "modules" command

=head1 SYNOPSIS

  invoke_iccr  {ncv arguments}

=head1 DESCRIPTION

=head1 DISTRIBUTION

Copyright 2007-2016 by Wilson Snyder.  This package is free software; you
can redistribute it and/or modify it under the terms of either the GNU
Lesser General Public License Version 3 or the Perl Artistic License
Version 2.0.

=head1 AUTHORS

Wilson Snyder <wsnyder@wsnyder.org>

=head1 SEE ALSO

=cut

######################################################################
### Local Variables:
### compile-command: "./invoke_iccr -help"
### End:
