name: lintly

# lintly does not support other than pull request
on:
  pull_request_target:

jobs:
  lintly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install flake8 lintly
      - name: Lint with flake8
#        run: flake8 --extend-exclude=fastcov.py | lintly
        run: flake8 --extend-exclude=fastcov.py
        env:
          LINTLY_API_KEY: ${{ secrets.GITHUB_TOKEN }}
