---
# DESCRIPTION: Github actions config
# SPDX-License-Identifier: LGPL-3.0-only OR Artistic-2.0

name: reusable-lint-py

on:
  workflow_call:

defaults:
  run:
    shell: bash
    working-directory: repo

jobs:

  lint-py:
    runs-on: ubuntu-22.04
    name: Sub-lint | Python
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7
        with:
          path: repo

      - name: Install dependencies
        run: |
          ./ci/ci-install.bash build
          sudo apt install python3-clang || \
          sudo apt install python3-clang

      - name: Configure
        run: |
          autoconf
          ./configure --enable-longtests --enable-ccwarn

      - name: Set up Python venv
        uses: ./repo/.github/actions/setup-venv
        with:
          save: ${{ github.ref == 'refs/heads/master' }}

      - name: Lint
        run: |-
          source .venv/bin/activate
          make -k lint-py
